# Nvidia's optimized MXNet image
FROM nvcr.io/nvidia/mxnet:21.04-py3

# Sockeye Python dependencies
ARG REQS
ARG REQS_HOROVOD
RUN pip install --no-cache-dir ${REQS} ${REQS_HOROVOD}

# Sockeye version
ARG SOCKEYE_COMMIT

# Install Sockeye
COPY . /opt/sockeye
RUN cd /opt/sockeye && \
    pip install --no-cache-dir --no-deps --editable .
