theme: jekyll-theme-minimal
title: Sockeye
description: A tool for sequence-to-sequence modeling
repository: awslabs/sockeye
markdown: kramdown
highlighter: rouge
url: https://awslabs.github.io
base_url: /sockeye
relative-links:
  enabled: true
  include:
    - tutorials