# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Sockeye requirements
      run: pip install -r requirements/requirements.txt
    - name: Development requirements
      run: pip install -r requirements/requirements.dev.txt
    - name: Unit tests
      run: |
        pytest --version
        pytest
    - name: Check manifest
      run: check-manifest --ignore sockeye/git_version.py
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_SECURE }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
